version: "3.8"

services:
  postgresdb:
    image: postgres
    restart: unless-stopped

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgres

  app:
    depends_on:
      - postgresdb
    build: .


    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: