spring:
  application:
    name: library
    issue:
      max_allowed-books: 3

  kafka:
    producer:
      bootstrap-servers: "127.0.0.1:9092"
      client-id: "demo-producer"

  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
#    hibernate:
#      ddl-auto:  create

management:
  endpoint:
    env:
      show-values: always
  endpoints:
    web:
      exposure:
        include: env, prometheus, health, info, metric


